In [6]:
import pandas as pd
from collections import Counter 
from sklearn.preprocessing import LabelEncoder 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_absolute_error 
from sklearn.metrics import r2_score

In [5]:
df = pd.read_csv("abalone.csv")

In [7]:
df.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [8]:
df.describe()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sex             4177 non-null   object
 1   Length          4177 non-null   float64
 2   Diameter        4177 non-null   float64
 3   Height          4177 non-null   float64
 4   Whole weight    4177 non-null   float64
 5   Shucked weight  4177 non-null   float64
 6   Viscera weight  4177 non-null   float64
 7   Shell weight    4177 non-null   float64
 8   Rings           4177 non-null   int64
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB

In [12]:
x=df.drop('Rings',axis=1)
y =df['Rings']

In [13]:
x.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055

In [14]:
x.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055

In [16]:
Counter(y)

Counter({9: 689,
         10: 634,
         8: 568,
         11: 487,
         7: 391,
         12: 267,
         6: 259,
         13: 203,
         14: 126,
         5: 115,
         15: 103,
         16: 67,
         17: 58,
         4: 57,
         18: 42,
         19: 32,
         20: 26,
         3: 15,
         21: 14,
         23: 9,
         22: 6,
         27: 2,
         24: 2,
         1: 1,
         26: 1,
         29: 1,
         2: 1,
         25: 1})

In [20]:
enc =LabelEncoder()
x['Sex']=enc.fit_transform(x['Sex'])
set(x['Sex'])

{0, 1, 2}

In [21]:
df.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [22]:
x_train,x_test,y_test,y_train = train_test_split(x,y,random_state=0,test_size=0.25)

In [23]:
len(x_train)

3132

In [24]:
len(x_test)

1045

In [25]:
x_train.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight
940,1,0.460,0.345,0.105,0.4490,0.1960,0.0945,0.1265
2688,2,0.630,0.465,0.150,1.0270,0.5370,0.1880,0.1760
1948,2,0.635,0.515,0.165,1.2290,0.5055,0.2975,0.3535
713,2,0.355,0.265,0.085,0.2010,0.0690,0.0530,0.0695
3743,0,0.705,0.555,0.195,1.7525,0.7105,0.4215,0.5160

In [31]:
clf=GaussianNB()
clf.fit(x_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [3132, 1045]

In [32]:
y_pred = clf.predict(x_test) 
accuracy_score(y_test, y_pred) * 100

AttributeError: 'GaussianNB' object has no attribute 'class_prior_'

In [33]:
print(classification_report(y_test,y_pred))

NameError: name 'y_pred' is not defined